version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  web:
    image: wordpress:4.9-apache
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html/
    ports:
      - "80:80"
