version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  web:
    image: vsplate/wordpress-4.6
    depends_on:
      - db
    ports:
      - "80:80"
