version: '3'

services:
  db:
    image: mysql:5.7
    environment:
       MYSQL_ROOT_PASSWORD: toor
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
  web:
    depends_on:
       - db
    image: vsplate/deb_apache2_php7_mysql5:latest
    volumes:
      - ./wordpress/:/var/www/html/
    ports:
      - "80:80"
